@startuml BillsGeneratorC2

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!define FONTAWESOME https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/font-awesome-5
!define DEVICONS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons2

!include DEVICONS/phoenix.puml
!include DEVICONS/postgresql.puml
!include DEVICONS/elixir.puml
!include FONTAWESOME/euro_sign.puml

HIDE_STEREOTYPE()
LAYOUT_WITH_LEGEND()


title BillsGenerator\nB<$euro_sign>G


Person_Ext(cliente, "Cliente", "Quere usar BillsGenerator")

'AddRelTag("Branco", $textColor="white", $lineColor="white")
AddElementTag("Branco",$bgColor="white")
AddElementTag("Gris",$bgColor="grey")
System_Boundary(sistema, "BillsGenerator") {
  System(frontend,"Frontend","UI para a xeración e descarga de facturas",$sprite="phoenix")
  System(backend, "Backend", "Xestiona facturas a nome dun cliente polo compra de distintos produtos",$sprite="elixir",$tags="branco"){
Container(filtroValidator,"Validator","Filtro que valida unha factura")
Container(filtroParser,"Parser","Filtro que parsea un json")
Container(filtroUpdate,"Calculator","Filtro que actualiza os totais da factura")
Container(filtroGenerateLatex,"Formatter","Filtro que transforma a factura a Latex")
Container(filtroGeneratePdf,"PdfCompiler","Filtro que xera un pdf a partir dunha factura en latex")
Container(filtroStore,"Storer","Filtro que almacena o pdf xerado nunha BD")
ContainerDb(bd,"BD","Almacena as facturas xeradas",$sprite="postgresql")
}  
}

BiRel_D(cliente, frontend, "Usa", "REST")
Rel_R(frontend,backend,"Solicitude","API/json")
Rel_R(filtroStore,bd,"Almacena","binary")
Rel_U(bd,frontend,"Resposta","API/bin")
Rel_D(frontend,bd,"Petición","API/json")
Rel_R(filtroParser,filtroValidator,"Envía","Json")
Rel_R(filtroValidator,filtroUpdate,"Envía","Elixir Map")
Rel_R(filtroUpdate,filtroGenerateLatex,"Envía","Elixir Map")
Rel_R(filtroGenerateLatex,filtroGeneratePdf,"Envía","Elixir Map:Latex code")
Rel_R(filtroGeneratePdf,filtroStore,"Envía","Binary")

@enduml 