@startuml BillsGenerator.C3

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml
!define FONTAWESOME https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/font-awesome-5
!define DEVICONS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons2

!include DEVICONS/phoenix.puml
!include DEVICONS/postgresql.puml
!include DEVICONS/elixir.puml
!include FONTAWESOME/euro_sign.puml

HIDE_STEREOTYPE()
LAYOUT_WITH_LEGEND()


title BillsGenerator\nB<$euro_sign>G

Person_Ext(cliente, "Cliente", "Quere usar BillsGenerator")
System(frontend,"Phoenix","Web Fwk",$sprite="phoenix",$tags="branco")

System_Boundary(sistema, "BillsGenerator\n Backend\n<$elixir>") {

Component(filtroValidatorM,"Validator\nLeader","GenFilter")
Component(filtroParserM,"Parser\nLeader","GenFilter")
Component(filtroUpdateM,"Calculator\nLeader","GenFilter")
Component(filtroGenerateLatexM,"Formatter\nLeader","GenFilter")
Component(filtroGeneratePdfM,"PdfCompiler\nLeader","GenFilter")
Component(filtroStoreM,"Storer\nLeader","GenFilter")

package "Validator Workers" {
Component(filtroValidatorW,"T1","GenFilterWorker") 
Component(filtroValidatorWN,"TN","GenFilterWorker")
}

package "Parser Workers" {
Component(filtroParserW,"T1","GenFilterWorker")
Component(filtroParserWN,"TN","GenFilterWorker")
}

package "Calculator Workers" {
Component(filtroUpdateW,"T1","GenFilterWorker")
Component(filtroUpdateWN,"TN","GenFilterWorker")
}

package "Formatter Workers" {
Component(filtroGenerateLatexW,"T1","GenFilterWorker")
Component(filtroGenerateLatexWN,"TN","GenFilterWorker")
}

package "PdfCompiler Workers" {
Component(filtroGeneratePdfW,"T1","GenFilterWorker")
Component(filtroGeneratePdfWN,"TN","GenFilterWorker")
}

package "Storer Workers" {
Component(filtroStoreW,"T1","GenFilterWorker")
Component(filtroStoreWN,"TN","GenFilterWorker")
}
 ' }
  

ComponentDb(bd,"BD","Ecto",$sprite="postgresql")
  
}

BiRel_D(frontend,cliente, "Usa", "API/REST")


Rel_D(frontend,sistema,"Solicitude","API/json")
Rel_R(filtroStoreM,bd,"Almacena","binary")
Rel_D(bd,frontend,"Resposta","API/bin")
Rel_U(frontend,bd,"Petición","API/json")

Rel_R(filtroParserM,filtroValidatorM,"Envía","Json",)
Rel_R(filtroValidatorM,filtroUpdateM,"Envía","BillRequest")
Rel_R(filtroUpdateM,filtroGenerateLatexM,"Envía","BillRequest")
Rel_R(filtroGenerateLatexM,filtroGeneratePdfM,"Envía","BillRequest/Latex")
Rel_R(filtroGeneratePdfM,filtroStoreM,"Envía","BillRequest/Pdf")

'Poñer o tipo de dato/tecnoloxía que se intercambia???  
'Formato de exemplo-> Rel_D(filtroParserM,filtroParserW,"Solicita\nXestiona","Elixir tuple")
Rel_D(filtroParserM,filtroParserW,"Solicita\nXestiona")
Rel_D(filtroParserM,filtroParserWN,"Solicita\nXestiona")
Rel_U(filtroParserW,filtroParserM,"Resultado")
Rel_U(filtroParserWN,filtroParserM,"Resultado")


Rel_D(filtroValidatorM,filtroValidatorW,"Solicita\nXestiona")
Rel_D(filtroValidatorM,filtroValidatorWN,"Solicita\nXestiona")
Rel_U(filtroValidatorW,filtroValidatorM,"Resultado")
Rel_U(filtroValidatorWN,filtroValidatorM,"Resultado")


Rel_D(filtroUpdateM,filtroUpdateW,"Solicita\nXestiona")
Rel_D(filtroUpdateM,filtroUpdateWN,"Solicita\nXestiona")
Rel_U(filtroUpdateW,filtroUpdateM,"Resultado")
Rel_U(filtroUpdateWN,filtroUpdateM,"Resultado")


Rel_D(filtroGenerateLatexM,filtroGenerateLatexW,"Solicita\nXestiona")
Rel_D(filtroGenerateLatexM,filtroGenerateLatexWN,"Solicita\nXestiona")
Rel_U(filtroGenerateLatexW,filtroGenerateLatexM,"Resultado")
Rel_U(filtroGenerateLatexWN,filtroGenerateLatexM,"Resultado")

Rel_D(filtroGeneratePdfM,filtroGeneratePdfW,"Solicita\nXestiona")
Rel_D(filtroGeneratePdfM,filtroGeneratePdfWN,"Solicita\nXestiona")
Rel_U(filtroGeneratePdfW,filtroGeneratePdfM,"Resultado")
Rel_U(filtroGeneratePdfWN,filtroGeneratePdfM,"Resultado")

Rel_D(filtroStoreM,filtroStoreW,"Solicita\nXestiona")
Rel_D(filtroStoreM,filtroStoreWN,"Solicita\nXestiona")
Rel_U(filtroStoreW,filtroStoreM,"Solicita\nXestiona")
Rel_U(filtroStoreWN,filtroStoreM,"Solicita\nXestiona")


filtroValidatorW . filtroValidatorWN
filtroParserW . filtroParserWN
filtroUpdateW . filtroUpdateWN
filtroGenerateLatexW . filtroGenerateLatexWN
filtroGeneratePdfW . filtroGeneratePdfWN
filtroStoreW . filtroStoreWN

@enduml 