import Config

# For production, don't forget to configure the url host
# to something meaningful, Phoenix uses this information
# when generating URLs.
#
# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.

# Original lines. lines below are a copy from dev environ
# config :bills_generator_web, BillsGeneratorWeb.Endpoint,
#   url: [host: "example.com", port: 80],
#   cache_static_manifest: "priv/static/cache_manifest.json"

config :bills_generator, BillsGenerator.Repository.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "db",
  database: "bills_generator_prod",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

config :bills_generator_web, BillsGeneratorWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {0, 0, 0, 0}, port: 4000],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "7hix1u7OOWnHvrhjOpGL0+MdQBdFzDaIYH1fPKAVUwaYsAIQq3ScbGOrUsi4chNb",
  watchers: []

config :logger, level: :info
