@startuml duxir_context
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
left to right direction

System_Ext(client, "Cliente", "Quere enviar unha petición a un servizo determinado")
System(duxir, "Duxir", "Recibe peticións dos clientes, procésaas e devolve unha resposta")
Rel(client, duxir, "Envía", "petición")
Rel(duxir,client,"Devolve", "resposta")

@enduml