@startuml duxir_component
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml


System_Ext(client, "Cliente", "Quere enviar unha petición a un servizo determinado")
System_Boundary(duxir,"Duxir"){

	Container_Boundary(duxir_container,"Lider"){
		Component(core_leader,"Core.Leader","GenServer","Ten a api pública para os clientes. Redirixe as peticións aos traballadores, á vez que analiza a carga dos servizos e levanta ou para traballadores en función do estado dos servizos")
		Component(service_handler,"Core.ServiceHandler","Struct","Encárgase de manter o estado interno de cada servizo (traballadores libres, traballos asignados...)")
	}
	
	Container_Boundary(servizo_1,"Servizo 1"){
		Component(servizo_1_w1,"Traballador 1","Core.StandardServer", "Recibe peticións e devolve unha resposta de acordo á tarefa que realiza o servizo")
		Component(servizo_1_w2,"Traballador 2","Core.StandardServer", "Recibe peticións e devolve unha resposta de acordo á tarefa que realiza o servizo")
		Component(servizo_1_wn,"Traballador N","Core.StandardServer", "Recibe peticións e devolve unha resposta de acordo á tarefa que realiza o servizo")
	}
	Container_Boundary(servizo_2,"Servizo 2"){
		Component(servizo_2_w1,"Traballador 1","Core.StandardServer", "Recibe peticións e devolve unha resposta de acordo á tarefa que realiza o servizo")
	}

	Container_Boundary(servizo_n,"Servizo N"){
		Component(servizo_n_w1,"Traballador 1","Core.StandardServer", "Recibe peticións e devolve unha resposta de acordo á tarefa que realiza o servizo")
	}

}
Rel_D(client, core_leader, "Envía", "petición")

Rel_R(core_leader,service_handler,"Modifica ou consulta","estado")
Rel_L(service_handler,core_leader,"Devolve","estado")

Rel(core_leader, servizo_1_w1, "Redirixe", "petición")
Rel(core_leader, servizo_1_w2, "Redirixe", "petición")
Rel(core_leader, servizo_1_wn, "Redirixe", "petición")
Rel(core_leader, servizo_2_w1, "Redirixe", "petición")
Rel(core_leader, servizo_n_w1, "Redirixe", "petición")

Rel(servizo_1_w1,core_leader, "Devolve", "resposta")
Rel(servizo_1_w2,core_leader, "Devolve", "resposta")
Rel(servizo_1_wn,core_leader, "Devolve", "resposta")
Rel(servizo_2_w1,core_leader, "Devolve", "resposta")
Rel(servizo_n_w1,core_leader, "Devolve", "resposta")

Rel_U(core_leader,client,"Devolve", "resposta")



@enduml